# This is a basic workflow to help you get started with Actions

name: GitHub Pages demo

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  demo-update:

    name: Update demo
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Install
      run: npm i
        
    - name: Build
      run: npm run build

    - name: Copy build
      run: cp -rT ./public ./gh-pages

    - name: Check for changes
      id: check-demo-changed
      run: |
        cd ./gh-pages
        git add --all
        git diff-index --cached --quiet HEAD -- || echo "::set-output name=has-changed::true"
    - name: Commit changes
      if: steps.check-demo-changed.outputs.has-changed == 'true'
      run: |
        cd ./gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update demo"
    - name: Push changes to GitHub Pages
      if: steps.check-demo-changed.outputs.has-changed == 'true'
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: gh-pages
        branch: gh-pages
